name: GH Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  pages:
    permissions:
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: actions/checkout@v4
      - name: Build
        run: |
          yarn
          yarn build
          cp demo/* dist/
      - name: Add and commit
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist'
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist/'
      - name: Deploy to GH Pages
        uses: actions/deploy-pages@v4
